AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda que processa o stream do DynamoDB ChatMemory e grava arquivos no S3 chat-memory-history

Parameters:
  ChatMemoryTableStreamArn:
    Type: String
    Description: ARN do stream da tabela ChatMemory
  ChatMemoryHistoryBucketName:
    Type: String
    Description: Nome do bucket S3 chat-memory-history

Resources:
  ChatMemoryStreamProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  ChatMemoryStreamProcessorRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ChatMemoryStreamProcessorPolicy
      Roles:
        - !Ref ChatMemoryStreamProcessorRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:DescribeStream
              - dynamodb:ListStreams
            Resource: !Ref ChatMemoryTableStreamArn
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub "arn:aws:s3:::${ChatMemoryHistoryBucketName}/*"

  ChatMemoryStreamProcessor:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: chat-memory-stream-to-s3
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt ChatMemoryStreamProcessorRole.Arn
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          BUCKET_NAME: !Ref ChatMemoryHistoryBucketName
      Code:
        ZipFile: |
          import json
          import os
          import boto3
          from datetime import datetime
          from decimal import Decimal
          from boto3.dynamodb.types import TypeDeserializer

          deserializer = TypeDeserializer()

          def deserialize_dynamodb(item):
              if item is None:
                  return None
              return {k: deserializer.deserialize(v) for k, v in item.items()}

          def decimal_default(obj):
              if isinstance(obj, Decimal):
                  return str(obj)
              raise TypeError

          def handler(event, context):
              s3 = boto3.client('s3')
              bucket = os.environ['BUCKET_NAME']
              records = []
              for record in event.get('Records', []):
                  if record.get('eventName') not in ('INSERT', 'MODIFY'):
                      continue
                  dynamodb = record.get('dynamodb', {})
                  payload = {
                      'eventId': record.get('eventID'),
                      'eventName': record.get('eventName'),
                      'eventTime': dynamodb.get('ApproximateCreationDateTime'),
                      'newImage': deserialize_dynamodb(dynamodb.get('NewImage')),
                      'oldImage': deserialize_dynamodb(dynamodb.get('OldImage'))
                  }
                  records.append(payload)
              if not records:
                  return {'processed': 0}
              timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
              key = f"chat-memory/stream/{timestamp}_{context.aws_request_id}.json"
              body = json.dumps(records, default=decimal_default, ensure_ascii=False)
              s3.put_object(Bucket=bucket, Key=key, Body=body, ContentType='application/json')
              return {'processed': len(records), 's3Key': key}

  ChatMemoryStreamEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn: ChatMemoryStreamProcessorRolePolicy
    Properties:
      EventSourceArn: !Ref ChatMemoryTableStreamArn
      FunctionName: !Ref ChatMemoryStreamProcessor
      StartingPosition: LATEST
      BatchSize: 100
      MaximumBatchingWindowInSeconds: 5
      FilterCriteria:
        Filters:
          - Pattern: '{"eventName": ["INSERT", "MODIFY"]}'

Outputs:
  ChatMemoryStreamProcessorArn:
    Description: ARN da Lambda chat-memory-stream-to-s3
    Value: !GetAtt ChatMemoryStreamProcessor.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ChatMemoryStreamProcessorArn"
